INSERT INTO sources (slug, name, type, trust_weight, x_handle, country_code)
VALUES
  ('orfbreakingnews', 'ORFBreakingNews', 'news', 0.500, 'ORFBreakingNews', 'AT'),
  ('derstandardat', 'derStandardat', 'news', 0.500, 'derStandardat', 'AT'),
  ('krone_at', 'krone_at', 'news', 0.500, 'krone_at', 'AT'),
  ('heute_at', 'heute.at', 'news', 0.500, 'heuteAT', 'AT'),
  ('oe24_at', 'OE24.at', 'news', 0.500, 'OE24at', 'AT'),
  ('wienerzeitung', 'Wiener Zeitung', 'news', 0.500, 'WienerZeitung', 'AT'),
  ('vrtnws', 'vrtnws', 'news', 0.500, 'vrtnws', 'BE'),
  ('rtbfinfo', 'RTBFinfo', 'news', 0.500, 'RTBFinfo', 'BE'),
  ('lesoir', 'lesoir', 'news', 0.500, 'lesoir', 'BE'),
  ('destandaard', 'De Standaard', 'news', 0.500, 'destandaard', 'BE'),
  ('hln_be', 'HLN.be', 'news', 0.500, 'HLNlive', 'BE'),
  ('ln24_be', 'LN24', 'news', 0.500, 'LN24_be', 'BE'),
  ('bnrhorizont', 'BNRHorizont', 'news', 0.500, 'BNRHorizont', 'BG'),
  ('btanewseng', 'BTAnewsENG', 'news', 0.500, 'BTAnewsENG', 'BG'),
  ('dnevnik', 'dnevnik', 'news', 0.500, 'dnevnik', 'BG'),
  ('novabg', 'Nova BG', 'news', 0.500, 'NovaBGnews', 'BG'),
  ('bgonair', 'BG ON AIR', 'news', 0.500, 'BGonAIR', 'BG'),
  ('offnews', 'OffNews', 'news', 0.500, 'offnews', 'BG'),
  ('hrtvijesti', 'hrtvijesti', 'news', 0.500, 'hrtvijesti', 'HR'),
  ('indexhr', 'indexhr', 'news', 0.500, 'indexhr', 'HR'),
  ('jutarnjihr', 'jutarnjihr', 'news', 0.500, 'jutarnjihr', 'HR'),
  ('vecernji_hr', 'Vecernji List', 'news', 0.500, 'vecernji_hr', 'HR'),
  ('telegram_hr', 'Telegram.hr', 'news', 0.500, 'telegramhr', 'HR'),
  ('tportal_hr', 'tportal.hr', 'news', 0.500, 'tportalhr', 'HR'),
  ('cyprusmail', 'cyprusmail', 'news', 0.500, 'cyprusmail', 'CY'),
  ('philenewscy', 'philenewscy', 'news', 0.500, 'philenewscy', 'CY'),
  ('sigmalive_en', 'Sigmalive_EN', 'news', 0.500, 'Sigmalive_EN', 'CY'),
  ('incyprus', 'In-Cyprus', 'news', 0.500, 'InCyprusNews', 'CY'),
  ('cna_cy', 'Cyprus News Agency', 'news', 0.500, 'CY_CNA', 'CY'),
  ('stockwatch_cy', 'StockWatch Cyprus', 'news', 0.500, 'StockWatchCY', 'CY'),
  ('ct24zive', 'CT24zive', 'news', 0.500, 'CT24zive', 'CZ'),
  ('idnescz', 'iDNEScz', 'news', 0.500, 'iDNEScz', 'CZ'),
  ('novinkycz', 'novinkycz', 'news', 0.500, 'novinkycz', 'CZ'),
  ('irozhlas', 'iROZHLAS', 'news', 0.500, 'irozhlascz', 'CZ'),
  ('denikcz', 'Denik.cz', 'news', 0.500, 'DenikCZ', 'CZ'),
  ('bleskcz', 'Blesk.cz', 'news', 0.500, 'Bleskzpravy', 'CZ'),
  ('drbreaking', 'DRBreaking', 'news', 0.500, 'DRBreaking', 'DK'),
  ('tv2newsdk', 'tv2newsdk', 'news', 0.500, 'tv2newsdk', 'DK'),
  ('berlingske', 'berlingske', 'news', 0.500, 'berlingske', 'DK'),
  ('ekstrabladet', 'Ekstra Bladet', 'news', 0.500, 'EkstraBladet', 'DK'),
  ('borsen_dk', 'Borsen', 'news', 0.500, 'Borsen_dk', 'DK'),
  ('jp_dk', 'Jyllands-Posten', 'news', 0.500, 'JyllandsPosten', 'DK'),
  ('errnews', 'errnews', 'news', 0.500, 'errnews', 'EE'),
  ('err_ee', 'err_ee', 'news', 0.500, 'err_ee', 'EE'),
  ('postimees', 'postimees', 'news', 0.500, 'postimees', 'EE'),
  ('delfi_ee', 'Delfi EE', 'news', 0.500, 'DelfiEesti', 'EE'),
  ('ohtuleht', 'Ohtuleht', 'news', 0.500, 'Ohtuleht', 'EE'),
  ('epl_ee', 'Eesti Paevaleht', 'news', 0.500, 'EPLee', 'EE'),
  ('ylenews', 'ylenews', 'news', 0.500, 'ylenews', 'FI'),
  ('yleuutiset', 'yleuutiset', 'news', 0.500, 'yleuutiset', 'FI'),
  ('hsfi', 'hsfi', 'news', 0.500, 'hsfi', 'FI'),
  ('iltasanomat', 'Iltasanomat', 'news', 0.500, 'iltasanomat', 'FI'),
  ('stt_fi', 'STT', 'news', 0.500, 'STTuutiset', 'FI'),
  ('aamulehti', 'Aamulehti', 'news', 0.500, 'aamulehti', 'FI'),
  ('franceinfo', 'franceinfo', 'news', 0.500, 'franceinfo', 'FR'),
  ('lemondefr', 'lemondefr', 'news', 0.500, 'lemondefr', 'FR'),
  ('ici_officiel', 'ici_officiel', 'news', 0.500, 'ici_officiel', 'FR'),
  ('leparisien', 'Le Parisien', 'news', 0.500, 'Le_Parisien', 'FR'),
  ('bfm_tv', 'BFM TV', 'news', 0.500, 'BFMTV', 'FR'),
  ('lefigaro', 'Le Figaro', 'news', 0.500, 'Le_Figaro', 'FR'),
  ('tagesschau', 'tagesschau', 'news', 0.500, 'tagesschau', 'DE'),
  ('zdfheute', 'ZDFheute', 'news', 0.500, 'ZDFheute', 'DE'),
  ('derspiegel', 'derspiegel', 'news', 0.500, 'derspiegel', 'DE'),
  ('bild', 'BILD', 'news', 0.500, 'BILD', 'DE'),
  ('faz_net', 'FAZ.NET', 'news', 0.500, 'FAZ_NET', 'DE'),
  ('welt', 'WELT', 'news', 0.500, 'welt', 'DE'),
  ('ertnews_gr', 'ERTnews_gr', 'news', 0.500, 'ERTnews_gr', 'GR'),
  ('ekathimerini', 'ekathimerini', 'news', 0.500, 'ekathimerini', 'GR'),
  ('ta_nea', 'ta_nea', 'news', 0.500, 'ta_nea', 'GR'),
  ('protothema', 'ProtoThema', 'news', 0.500, 'ProtoThema', 'GR'),
  ('skai_gr', 'SKAI TV', 'news', 0.500, 'skaigr', 'GR'),
  ('cnn_gr', 'CNN Greece', 'news', 0.500, 'CNN_gr', 'GR'),
  ('hungarytoday', 'HungaryToday', 'news', 0.500, 'HungaryToday', 'HU'),
  ('telexhu', 'telexhu', 'news', 0.500, 'telexhu', 'HU'),
  ('hvg_hu', 'hvg_hu', 'news', 0.500, 'hvg_hu', 'HU'),
  ('index_hu', 'Index.hu', 'news', 0.500, 'indexhu', 'HU'),
  ('444_hu', '444.hu', 'news', 0.500, '444hu', 'HU'),
  ('mandiner', 'Mandiner', 'news', 0.500, 'mandinerhu', 'HU'),
  ('rtenews', 'rtenews', 'news', 0.500, 'rtenews', 'IE'),
  ('irishtimes', 'IrishTimes', 'news', 0.500, 'IrishTimes', 'IE'),
  ('thejournal_ie', 'thejournal_ie', 'news', 0.500, 'thejournal_ie', 'IE'),
  ('irishmirror', 'Irish Mirror', 'news', 0.500, 'IrishMirror', 'IE'),
  ('indo_ie', 'Irish Independent', 'news', 0.500, 'IndoNews', 'IE'),
  ('breakingnews_ie', 'BreakingNews.ie', 'news', 0.500, 'BreakingNewsIE', 'IE'),
  ('agenzia_ansa', 'Agenzia_Ansa', 'news', 0.500, 'Agenzia_Ansa', 'IT'),
  ('rainews', 'RaiNews', 'news', 0.500, 'RaiNews', 'IT'),
  ('ilpost', 'ilpost', 'news', 0.500, 'ilpost', 'IT'),
  ('repubblica', 'la Repubblica', 'news', 0.500, 'repubblica', 'IT'),
  ('corriere', 'Corriere della Sera', 'news', 0.500, 'Corriere', 'IT'),
  ('lastampa', 'La Stampa', 'news', 0.500, 'LaStampa', 'IT'),
  ('lsm_eng', 'LSM_eng', 'news', 0.500, 'LSM_eng', 'LV'),
  ('lsmlv', 'lsmlv', 'news', 0.500, 'lsmlv', 'LV'),
  ('delfilv', 'DelfiLV', 'news', 0.500, 'DelfiLV', 'LV'),
  ('la_lv', 'Latvijas Avizes', 'news', 0.500, 'LA_LV', 'LV'),
  ('tv3latvia', 'TV3 Latvia', 'news', 0.500, 'TV3Latvia', 'LV'),
  ('delfi_lv_en', 'Delfi LV English', 'news', 0.500, 'DelfiLvEn', 'LV'),
  ('lrtenglish', 'LRTenglish', 'news', 0.500, 'LRTenglish', 'LT'),
  ('lrtlt', 'lrtlt', 'news', 0.500, 'lrtlt', 'LT'),
  ('delfilt', 'DelfiLT', 'news', 0.500, 'DelfiLT', 'LT'),
  ('15min_lt', '15min.lt', 'news', 0.500, '15min_lt', 'LT'),
  ('lrytas', 'Lrytas.lt', 'news', 0.500, 'Lrytas_lt', 'LT'),
  ('delfi_lt_en', 'Delfi LT English', 'news', 0.500, 'DelfiEn', 'LT'),
  ('rtltoday', 'RTLtoday', 'news', 0.500, 'RTLtoday', 'LU'),
  ('rtllu', 'RTLlu', 'news', 0.500, 'RTLlu', 'LU'),
  ('wort_lu', 'Wort_LU', 'news', 0.500, 'Wort_LU', 'LU'),
  ('chronicle_lu', 'Chronicle LU', 'news', 0.500, 'ChronicleLU', 'LU'),
  ('delano_lu', 'Delano', 'news', 0.500, 'DelanoLU', 'LU'),
  ('wort_lu_2', 'Luxemburger Wort', 'news', 0.500, 'LuxWort', 'LU'),
  ('timesofmalta', 'timesofmalta', 'news', 0.500, 'timesofmalta', 'MT'),
  ('maltatoday', 'MaltaToday', 'news', 0.500, 'MaltaToday', 'MT'),
  ('tvmnews_mt', 'TVMnews_MT', 'news', 0.500, 'TVMnews_MT', 'MT'),
  ('newsbook_mt', 'Newsbook Malta', 'news', 0.500, 'NewsbookMT', 'MT'),
  ('maltaindependent', 'Malta Independent', 'news', 0.500, 'MaltaInd', 'MT'),
  ('netnews_mt', 'NET News Malta', 'news', 0.500, 'NetNewsMT', 'MT'),
  ('nos', 'NOS', 'news', 0.500, 'NOS', 'NL'),
  ('nunl', 'NUnl', 'news', 0.500, 'NUnl', 'NL'),
  ('telegraaf', 'telegraaf', 'news', 0.500, 'telegraaf', 'NL'),
  ('ad_nl', 'AD.nl', 'news', 0.500, 'ADnl', 'NL'),
  ('rtlnieuws', 'RTL Nieuws', 'news', 0.500, 'RTLnieuws', 'NL'),
  ('volkskrant', 'de Volkskrant', 'news', 0.500, 'volkskrant', 'NL'),
  ('papinformacje', 'PAPinformacje', 'news', 0.500, 'PAPinformacje', 'PL'),
  ('tvp_info', 'tvp_info', 'news', 0.500, 'tvp_info', 'PL'),
  ('wyborcza', 'wyborcza', 'news', 0.500, 'wyborcza', 'PL'),
  ('rzeczpospolita', 'Rzeczpospolita', 'news', 0.500, 'Rzepapl', 'PL'),
  ('onet_pl', 'Onet Wiadomosci', 'news', 0.500, 'OnetWiadomosci', 'PL'),
  ('tvn24', 'TVN24', 'news', 0.500, 'tvn24', 'PL'),
  ('rtpnoticias', 'RTPNoticias', 'news', 0.500, 'RTPNoticias', 'PT'),
  ('publico', 'Publico', 'news', 0.500, 'Publico', 'PT'),
  ('observadorpt', 'observadorpt', 'news', 0.500, 'observadorpt', 'PT'),
  ('sicnoticias', 'SIC Noticias', 'news', 0.500, 'SICNoticias', 'PT'),
  ('cmtv_pt', 'CM TV', 'news', 0.500, 'CMTVpt', 'PT'),
  ('jn_pt', 'Jornal de Noticias', 'news', 0.500, 'JNpt', 'PT'),
  ('agerpres', 'agerpres', 'news', 0.500, 'agerpres', 'RO'),
  ('digi24_hd', 'Digi24_HD', 'news', 0.500, 'Digi24_HD', 'RO'),
  ('hotnews_ro', 'hotnews_ro', 'news', 0.500, 'hotnews_ro', 'RO'),
  ('stirileprotv', 'Stirile PROTV', 'news', 0.500, 'stirilePROTV', 'RO'),
  ('radioromania', 'Radio Romania', 'news', 0.500, 'RadioRom', 'RO'),
  ('digi24_ro', 'Digi24.ro', 'news', 0.500, 'Digi24ro', 'RO'),
  ('tasrnews', 'TASRnews', 'news', 0.500, 'TASRnews', 'SK'),
  ('rtvs', 'RTVS', 'news', 0.500, 'RTVS', 'SK'),
  ('denniksme', 'DennikSME', 'news', 0.500, 'DennikSME', 'SK'),
  ('aktuality_sk', 'Aktuality.sk', 'news', 0.500, 'AktualitySK', 'SK'),
  ('novycas_sk', 'Novy Cas', 'news', 0.500, 'NovyCasSK', 'SK'),
  ('hnonline_sk', 'HNonline.sk', 'news', 0.500, 'HNonlineSK', 'SK'),
  ('rtvslo', 'rtvslo', 'news', 0.500, 'rtvslo', 'SI'),
  ('sta_novice', 'STA_novice', 'news', 0.500, 'STA_novice', 'SI'),
  ('24ur_com', '24ur_com', 'news', 0.500, '24ur_com', 'SI'),
  ('nova24tv', 'Nova24TV', 'news', 0.500, 'Nova24TV', 'SI'),
  ('reporter_si', 'Reporter.si', 'news', 0.500, 'ReporterSI', 'SI'),
  ('slovenia_info', 'Slovenia.info', 'news', 0.500, 'SloveniaInfo', 'SI'),
  ('rtvenoticias', 'rtvenoticias', 'news', 0.500, 'rtvenoticias', 'ES'),
  ('efenoticias', 'EFEnoticias', 'news', 0.500, 'EFEnoticias', 'ES'),
  ('el_pais', 'el_pais', 'news', 0.500, 'el_pais', 'ES'),
  ('elmundo', 'El Mundo', 'news', 0.500, 'elmundoes', 'ES'),
  ('abc_es', 'ABC.es', 'news', 0.500, 'ABCes', 'ES'),
  ('lavanguardia', 'La Vanguardia', 'news', 0.500, 'LaVanguardia', 'ES'),
  ('svtnyheter', 'svtnyheter', 'news', 0.500, 'svtnyheter', 'SE'),
  ('sr_ekot', 'sr_ekot', 'news', 0.500, 'sr_ekot', 'SE'),
  ('aftonbladet', 'Aftonbladet', 'news', 0.500, 'Aftonbladet', 'SE'),
  ('dn_se', 'Dagens Nyheter', 'news', 0.500, 'DN_se', 'SE'),
  ('expressen', 'Expressen', 'news', 0.500, 'Expressen', 'SE'),
  ('tt_se', 'TT Nyhetsbyran', 'news', 0.500, 'TT_se', 'SE')
ON CONFLICT (slug) DO UPDATE
SET name = EXCLUDED.name,
    x_handle = EXCLUDED.x_handle,
    country_code = EXCLUDED.country_code,
    enabled = true,
    updated_at = now();
